version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '06:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:30'
      timezone: Asia/Kolkata
    open-pull-requests-limit: 10
