// Generated by scripts/generate-locale-docs.mjs. Do not edit directly.
export type GeneratedLocaleCode =
  | 'af-ZA'
  | 'am-ET'
  | 'ar-AE'
  | 'ar-DZ'
  | 'ar-EG'
  | 'ar-IQ'
  | 'ar-LB'
  | 'ar-MA'
  | 'ar-SA'
  | 'ar-SD'
  | 'ar-YE'
  | 'as-IN'
  | 'az-AZ'
  | 'be-BY'
  | 'bg-BG'
  | 'bn-BD'
  | 'bn-IN'
  | 'ca-ES'
  | 'cs-CZ'
  | 'da-DK'
  | 'de-AT'
  | 'de-CH'
  | 'de-DE'
  | 'ee-EE'
  | 'el-GR'
  | 'en-AE'
  | 'en-AU'
  | 'en-BD'
  | 'en-CA'
  | 'en-GB'
  | 'en-GH'
  | 'en-HK'
  | 'en-IE'
  | 'en-IN'
  | 'en-IQ'
  | 'en-JM'
  | 'en-KE'
  | 'en-LK'
  | 'en-MA'
  | 'en-MM'
  | 'en-MU'
  | 'en-MY'
  | 'en-NG'
  | 'en-NP'
  | 'en-NZ'
  | 'en-OM'
  | 'en-PH'
  | 'en-PK'
  | 'en-SA'
  | 'en-SG'
  | 'en-TT'
  | 'en-TZ'
  | 'en-UG'
  | 'en-US'
  | 'en-ZA'
  | 'en-ZW'
  | 'es-AR'
  | 'es-CL'
  | 'es-CO'
  | 'es-ES'
  | 'es-MX'
  | 'es-PE'
  | 'es-US'
  | 'es-VE'
  | 'fa-IR'
  | 'fi-FI'
  | 'fil-PH'
  | 'fr-BE'
  | 'fr-CA'
  | 'fr-CH'
  | 'fr-CI'
  | 'fr-CM'
  | 'fr-DZ'
  | 'fr-FR'
  | 'fr-MA'
  | 'fr-MG'
  | 'fr-SA'
  | 'gu-IN'
  | 'ha-NG'
  | 'hbo-IL'
  | 'he-IL'
  | 'hi-IN'
  | 'hr-HR'
  | 'hu-HU'
  | 'id-ID'
  | 'ig-NG'
  | 'is-IS'
  | 'it-IT'
  | 'ja-JP'
  | 'jv-ID'
  | 'ka-GE'
  | 'km-KH'
  | 'kn-IN'
  | 'ko-KR'
  | 'lt-LT'
  | 'lv-LV'
  | 'ml-IN'
  | 'mr-IN'
  | 'ms-MY'
  | 'ms-SG'
  | 'my-MM'
  | 'nb-NO'
  | 'nl-NL'
  | 'nl-SR'
  | 'np-NP'
  | 'or-IN'
  | 'pa-IN'
  | 'pl-PL'
  | 'pt-AO'
  | 'pt-BR'
  | 'pt-MZ'
  | 'pt-PT'
  | 'ro-RO'
  | 'ru-RU'
  | 'si-LK'
  | 'sk-SK'
  | 'sl-SI'
  | 'sq-AL'
  | 'sr-RS'
  | 'sv-SE'
  | 'sw-KE'
  | 'sw-TZ'
  | 'ta-IN'
  | 'te-IN'
  | 'th-TH'
  | 'tr-TR'
  | 'uk-UA'
  | 'ur-PK'
  | 'uz-UZ'
  | 'vi-VN'
  | 'yo-NG'
  | 'yue-HK'
  | 'zh-CN'
  | 'zh-TW'
  | 'zu-ZA';

type LocaleCapabilityDatum = Readonly<{
  ordinal: boolean;
  formal: boolean;
  cardinalGender: boolean;
  ordinalGender: boolean;
  fractionDigits: readonly number[];
  currencyPrecision: number;
}>;

export const LOCALE_CAPABILITY_DATA: Readonly<Record<GeneratedLocaleCode, LocaleCapabilityDatum>> = {
  'af-ZA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'am-ET': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-AE': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-DZ': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-EG': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-IQ': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 3,
  },
  'ar-LB': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-MA': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-SA': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-SD': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ar-YE': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'as-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'az-AZ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'be-BY': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'bg-BG': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'bn-BD': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'bn-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ca-ES': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'cs-CZ': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'da-DK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'de-AT': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'de-CH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'de-DE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ee-EE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'el-GR': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-AE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-AU': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-BD': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-CA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-GB': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-GH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-HK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-IE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-IQ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 3,
  },
  'en-JM': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-KE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-LK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-MA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-MM': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-MU': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-MY': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-NG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-NP': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-NZ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-OM': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 3,
  },
  'en-PH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-PK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-SA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-SG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-TT': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-TZ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-UG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-US': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-ZA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'en-ZW': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-AR': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-CL': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-CO': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-ES': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-MX': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-PE': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-US': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'es-VE': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: true,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fa-IR': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fi-FI': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'fil-PH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'fr-BE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-CA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-CH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-CI': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-CM': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-DZ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-FR': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-MA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-MG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'fr-SA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'gu-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ha-NG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'hbo-IL': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'he-IL': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'hi-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'hr-HR': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'hu-HU': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'id-ID': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ig-NG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'is-IS': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'it-IT': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ja-JP': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'jv-ID': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ka-GE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'km-KH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'kn-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ko-KR': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'lt-LT': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'lv-LV': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ml-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'mr-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ms-MY': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ms-SG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'my-MM': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'nb-NO': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'nl-NL': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'nl-SR': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'np-NP': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'or-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'pa-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'pl-PL': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'pt-AO': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'pt-BR': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'pt-MZ': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'pt-PT': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ro-RO': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ru-RU': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'si-LK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'sk-SK': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'sl-SI': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'sq-AL': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'sr-RS': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'sv-SE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'sw-KE': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'sw-TZ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'ta-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'te-IN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'th-TH': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'tr-TR': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'uk-UA': {
    ordinal: true,
    formal: false,
    cardinalGender: true,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'ur-PK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'uz-UZ': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'vi-VN': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [1, 2, 3, 4, 5, 6],
    currencyPrecision: 2,
  },
  'yo-NG': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'yue-HK': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'zh-CN': {
    ordinal: true,
    formal: true,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'zh-TW': {
    ordinal: true,
    formal: true,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
  'zu-ZA': {
    ordinal: true,
    formal: false,
    cardinalGender: false,
    ordinalGender: false,
    fractionDigits: [],
    currencyPrecision: 2,
  },
};
